language: java

before_install:
- cp .travis.settings.xml $HOME/.m2/settings.xml

jdk:
  - oraclejdk11

#before_install:
#  - sudo apt-get update
#  - sudo apt-get -y install calibre

cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.rvm
  - $HOME/.bundle
  - $HOME/bin/kindlegen/

script:
- ci/render-book-and-publish.sh
#- mvn -e verify deploy

env:
- SPRING_PROFILES_ACTIVE=ci
