language: bash



addons:
    apt:
        packages:
        - ghostscript
        # - dia
        # - inkscape
        # - r-base-core
        # - unoconv
        # - libreoffice
        # - poppler-utils
        # - texlive-extra-utils
        # - lintian


# before_install:
#  - ./setup-env.sh

jdk:
 - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.rvm 

script:
- ./setup-env.sh
# - ./onramp.sh

env:
- SPRING_PROFILES_ACTIVE=ci

