language: java

before_install:
- ./setup-env.sh

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.rvm 

script:
- echo "running script.."

env:
- SPRING_PROFILES_ACTIVE=ci

